用户指导
------------

本文档部分会告诉你如何开始使用 Flask-RESTful 与 Flask 一起工作。

.. toctree::
   :maxdepth: 2

   installation
   quickstart
   reqparse 
   fields
   extending
   intermediate-usage

API 手册
-------------

如果你想了解一个函数、类、或方法的具体信息，
请阅读 API 手册文档内容。

.. toctree::
   :maxdepth: 2

   api

另外注意事项
----------------

阅读 Flask 的协议 license_ 了解法律信息组织本项目。

.. toctree::
   :maxdepth: 2

   testing

.. _license: http://flask.pocoo.org/docs/license/

